version: "3"
services:
  mongo:
    image: mongo:3.2
    container_name: member
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: member
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --authenticationDatabase 'admin' -u 'admin' -p 'password' --quiet
      interval: 5s
      timeout: 1s
    ports:
      - "27017:27017"
    networks:
      - default
    command: >
      mongod --quiet
  
  retail:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/member?authSource=admin
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - default
    links:
      - mongo
    depends_on:
      - mongo
  
networks:
  default:
    driver: bridge

volumes:
  mongo: {}